name: Lint-code-check
 
on:
  push:
    branches:
      - '**'
    tags:
      - '**'
jobs:
  run-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npx eslint .

      - name: Run tests
        run: npx jest

      - name: Show test coverage
        run: npx jest --coverage

      - name: Test & publish code coverage
        # Publish code coverage on Code Climate
        # https://github.com/paambaati/codeclimate-action
        uses: paambaati/codeclimate-action@v2.7.4
        # Add Code Climate secret key
        env:
          CC_TEST_REPORTER_ID: 80d68191f3fe3853d4e8172cee93106ba47850984ec5162c5495742243e41c3a
        with:
          coverageCommand: make test-coverage
          debug: true