name: init-check
 
on:
  push:
    branches:
      - '**'
    tags:
      - '**'
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npx eslint .

      - name: Run tests
        run: npx jest

      - name: Show test coverage
        run: npx jest --coverage